# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程名字')),
                ('photo', models.ImageField(blank=True, max_length=200, null=True, upload_to='course/%Y/%m', verbose_name='课程封面')),
                ('time', models.IntegerField(default=0, verbose_name='课程时长')),
                ('student_count', models.IntegerField(verbose_name='学习人数')),
                ('is_collect', models.BooleanField(choices=[(0, '是'), (1, '否')], default=1, max_length=1, verbose_name='是否收藏')),
                ('level', models.CharField(default='入门', max_length=10, verbose_name='课程难度')),
                ('lesson_num', models.IntegerField(default=0, verbose_name='课程章节数')),
                ('has_fav', models.IntegerField(default=0, verbose_name='收藏人数')),
            ],
            options={
                'verbose_name': '课程列表',
                'verbose_name_plural': '课程列表',
            },
        ),
        migrations.CreateModel(
            name='Lessones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='教师姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('photo', models.ImageField(blank=True, max_length=200, null=True, upload_to='teacher/%Y/%m', verbose_name='用户头像')),
                ('is_admit', models.BooleanField(choices=[(0, '是'), (1, '否')], default=1, max_length=1, verbose_name='是否认证')),
                ('work_time', models.IntegerField(verbose_name='工作年限')),
                ('company', models.CharField(max_length=50, verbose_name='就职公司')),
                ('job', models.CharField(max_length=50, verbose_name='工作职位')),
                ('character', models.CharField(max_length=200, verbose_name='教学特点')),
                ('visit_num', models.IntegerField(default=0, verbose_name='浏览人数')),
                ('is_collect', models.BooleanField(choices=[(0, '是'), (1, '否')], default=1, max_length=1, verbose_name='是否收藏')),
                ('sex', models.CharField(default='男', max_length=10, verbose_name='性别')),
            ],
            options={
                'verbose_name': '教师表',
                'verbose_name_plural': '教师表',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_app.Teacher', verbose_name='教师姓名'),
        ),
    ]
